# Generated by Django 4.2.16 on 2024-11-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('realizada', models.BooleanField(default=False, verbose_name='Realizada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarefa.categoria')),
            ],
        ),
    ]
